---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-postgres-pvc
  namespace: forgejo-test
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-data-pvc
  namespace: forgejo-test
  labels:
    app: forgejo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi